FROM apache/airflow:2.8.1-python3.9

USER root
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    gcc \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

USER airflow

# Install Python dependencies
RUN pip install --no-cache-dir \
    fredapi \
    yfinance \
    pandas-datareader \
    python-dotenv \
    pyyaml \
    scikit-learn